[phases.setup]
nixPkgs = ["python39", "nodejs", "yarn"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt",
  "cd frontend && yarn install"
]

[phases.build]
cmds = [
  "cd frontend && yarn build"
]

[start]
cmd = "python -m uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"
