[phases.setup]
nixPkgs = ["python312", "nodejs-18_x", "yarn", "python312Packages.pip", "python312Packages.virtualenv"]

[phases.install]
cmds = [
  "virtualenv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt",
  "cd frontend && yarn install"
]

[phases.build]
cmds = [
  "cd frontend && yarn build",
  "cd .."
]

[start]
cmd = ". /opt/venv/bin/activate && python -m uvicorn src.api.main:app --host 0.0.0.0 --port ${PORT:-8000}"
