[phases.setup]
nixPkgs = ["python312", "nodejs-18_x", "yarn", "python312Packages.pip"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt",
  "cd frontend && yarn install"
]

[phases.build]
cmds = [
  "cd frontend && yarn build",
  "cd .."
]

[start]
cmd = "python -m uvicorn src.api.main:app --host 0.0.0.0 --port ${PORT:-8000}"
