[phases.setup]
nixPkgs = ["python312", "nodejs-18_x", "yarn"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && yarn install && yarn build"
]

[start]
cmd = "python -m uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"
